import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/header/Navbar';
import { Toaster } from 'sonner';
import Footer from '@/components/ui/Footer';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen bg-gradient-to-br from-orange-400 via-pink-500 to-blue-600 relative overflow-hidden flex flex-col">
          <Navbar />
          <main className="relative z-0 h-full flex-1">{children}</main>
          <Toaster richColors />
          <Footer />
        </div>
      </body>
    </html>
  );
}
